name: Mark stale issues

on:
  schedule:
  - cron: '0 1 * * *'

  workflow_dispatch:

jobs:
  stale:
    uses: configcat/.github/.github/workflows/stale.yml@master
    secrets: inherit

  # Prevent GitHub from suspending your cronjob based triggers due to repository inactivity
  keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2